IE.fModule({f:function(exports,require,module,global){"use strict";module.exports = function (lObjetImageConnexion) {
var TypeArrierePlanAuthentification = require('TypeArrierePlanAuthentification.js').TypeArrierePlanAuthentification
var ObjetImageConnexion = require('ObjetImageConnexion.js');
if (!ObjetImageConnexion) ObjetImageConnexion = lObjetImageConnexion;

var imagesExtra = {
    '9-1': {
      srcImage: 'ressources/dicosdor.gif',
      urlImageFond: 'ressources/dicosdor-background.jpg',
      widthImageSuite: 1330,
      heightImageSuite: 760,
      couleurConnexion: '#ffffff',
      classImageFond: 'Repeat',
      avecLien: true,
      lien: 'https://www.dicosdor-campus.fr/?utm_source=partenariat&utm_medium=web&utm_campaign=pronote_01_10_20 ',
      texteLien: 'En savoir plus sur le concours Les Dicos d\'Or Campus',
      suiviLien: 'https://www.index-education.com/swie/tl.php?ln=dicosdor',
      couleurLien: '#ffffff',
      bottomLien: '3%',
      leftLien: '12%',
      tailleLien: '100%'
    },

    '2-14': {
      srcImage: 'ressources/piday2021.png',
      urlImageFond: 'ressources/piday2021-background.jpg',
      widthImageSuite: 1330,
      heightImageSuite: 760,
      couleurConnexion: '#ffffff',
      classImageFond: 'Cover',
      avecLien: false
    },
 

};
ObjetImageConnexion.setDefinitionImagesExtra(imagesExtra);

var lImages = [];

lImages[TypeArrierePlanAuthentification.Louvre] = [{
  // Semaine 1
  srcImage: 'ressources/01_carmen.png',
  urlImageSuite: 'ressources/01_carmen-suite.png',
  urlImageFond: 'ressources/01_carmen-background.jpg',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_01_carmen',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 2
  srcImage: 'ressources/02_josef.png',
  urlImageSuite: 'ressources/02_josef-suite.jpg',
  urlImageFond: 'ressources/02_josef-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_02_josef',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 3
  srcImage: 'ressources/03_camille.png',
  urlImageSuite: 'ressources/03_camille-suite.jpg',
  urlImageFond: 'ressources/03_camille-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_03_camille',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 4
  srcImage: 'ressources/04_lila.png',
  urlImageSuite: 'ressources/04_lila-suite.jpg',
  urlImageFond: 'ressources/04_lila-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_04_lila',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 5
  srcImage: 'ressources/05_natan.jpg',
  urlImageSuite: 'ressources/05_natan-suite.jpg',
  urlImageFond: 'ressources/05_natan-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_05_natan',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 6
  srcImage: 'ressources/06_rosalie.png',
  urlImageSuite: 'ressources/06_rosalie-suite.png',
  urlImageFond: 'ressources/06_rosalie-background.jpg',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_06_rosalie',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 7
  srcImage: 'ressources/07_mina.jpg',
  urlImageSuite: 'ressources/07_mina-suite.jpg',
  urlImageFond: 'ressources/07_mina-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_07_mina',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 8
  srcImage: 'ressources/08_sybille.png',
  urlImageSuite: 'ressources/08_sybille-suite.png',
  urlImageFond: 'ressources/08_sybille-background.jpg',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_08_sybille',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 9
  srcImage: 'ressources/09_gabriel.jpg',
  urlImageSuite: 'ressources/09_gabriel-suite.jpg',
  urlImageFond: 'ressources/09_gabriel-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_09_gabriel',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 10
  srcImage: 'ressources/10_alice.jpg',
  urlImageSuite: 'ressources/10_alice-suite.jpg',
  urlImageFond: 'ressources/10_alice-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_10_alice',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 11
  srcImage: 'ressources/11_louna.png',
  urlImageSuite: 'ressources/11_louna-suite.png',
  urlImageFond: 'ressources/11_louna-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_11_louna',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 12
  srcImage: 'ressources/12_nestor.jpg',
  urlImageSuite: 'ressources/12_nestor-suite.jpg',
  urlImageFond: 'ressources/12_nestor-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_12_nestor',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 13
  srcImage: 'ressources/13_solene.png',
  urlImageSuite: 'ressources/13_solene-suite.png',
  urlImageFond: 'ressources/13_solene-background.jpg',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_13_solene',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 14
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 15
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 16
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 17
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 18
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 19
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 20
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 21
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 22
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 23
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 24
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 25
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 26
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 27
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 28
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 29
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 30
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 31
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 32
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 33
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 34
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 35
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 36
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 37
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 38
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 39
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 40
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 41
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 42
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 43
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 44
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 45
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 46
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 47
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus sur la formation FMA',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 48
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'Semaine 48',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 49
  srcImage: 'ressources/clara1.png',
  urlImageSuite: 'ressources/clara1-suite.png',
  urlImageFond: 'ressources/clara1-background.png',
  classImageFond: 'Repeat',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://ecole-boulle.org/',
  styleLogo: 'background-image: url(ressources/logo-ecole-boulle.png);width: 95px;height: 50px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=b_logo',
  avecLienSuite: true,
  texteLienSuite: 'Semaine 49 du 1 au 7 décembre',
  lienSuite: 'https://ecole-boulle.org/category/les-ateliers-et-formations/dfesma-fma/',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=b_clara1',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 50
  srcImage: 'ressources/saloncarre.png',
  urlImageSuite: 'ressources/saloncarre-suite.png',
  urlImageFond: 'ressources/saloncarre-background.png',
  classImageFond: 'Cover',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://www.louvre.fr/',
  styleLogo: 'background-image: url(ressources/logo-louvre.png);width: 110px;height: 33px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=l_saloncar',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus et découvrir l\'exposition Figure d\'artiste de la Petite Galerie du Louvre',
  lienSuite: 'https://petitegalerie.louvre.fr/oeuvre/le-salon-carr%C3%A9-en-1861?utm_campaign=pronotepg5&utm_medium=page_oeuvre&utm_source=pronote_castiglione',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=lpg_saloncar',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 51
  srcImage: 'ressources/saloncarre.png',
  urlImageSuite: 'ressources/saloncarre-suite.png',
  urlImageFond: 'ressources/saloncarre-background.png',
  classImageFond: 'Cover',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://www.louvre.fr/',
  styleLogo: 'background-image: url(ressources/logo-louvre.png);width: 110px;height: 33px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=l_saloncar',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus et découvrir l\'exposition Figure d\'artiste de la Petite Galerie du Louvre',
  lienSuite: 'https://petitegalerie.louvre.fr/oeuvre/le-salon-carr%C3%A9-en-1861?utm_campaign=pronotepg5&utm_medium=page_oeuvre&utm_source=pronote_castiglione',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=lpg_saloncar',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 52
  srcImage: 'ressources/saloncarre.png',
  urlImageSuite: 'ressources/saloncarre-suite.png',
  urlImageFond: 'ressources/saloncarre-background.png',
  classImageFond: 'Cover',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://www.louvre.fr/',
  styleLogo: 'background-image: url(ressources/logo-louvre.png);width: 110px;height: 33px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=l_saloncar',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus et découvrir l\'exposition Figure d\'artiste de la Petite Galerie du Louvre',
  lienSuite: 'https://petitegalerie.louvre.fr/oeuvre/le-salon-carr%C3%A9-en-1861?utm_campaign=pronotepg5&utm_medium=page_oeuvre&utm_source=pronote_castiglione',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=lpg_saloncar',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}, {
  // Semaine 53
  srcImage: 'ressources/saloncarre.png',
  urlImageSuite: 'ressources/saloncarre-suite.png',
  urlImageFond: 'ressources/saloncarre-background.png',
  classImageFond: 'Cover',
  widthImageSuite: 1330,
  heightImageSuite: 760,
  couleurConnexion: '#ffffff',
  lienLogo: 'https://www.louvre.fr/',
  styleLogo: 'background-image: url(ressources/logo-louvre.png);width: 110px;height: 33px;',
  suiviLogo: 'https://www.index-education.com/swie/tl.php?ln=l_saloncar',
  avecLienSuite: true,
  texteLienSuite: 'En savoir plus et découvrir l\'exposition Figure d\'artiste de la Petite Galerie du Louvre',
  lienSuite: 'https://petitegalerie.louvre.fr/oeuvre/le-salon-carr%C3%A9-en-1861?utm_campaign=pronotepg5&utm_medium=page_oeuvre&utm_source=pronote_castiglione',
  suiviLienSuite: 'https://www.index-education.com/swie/tl.php?ln=lpg_saloncar',
  dateMaxLien: new Date(1625443200000) // Thu Jul 05 2021 00:00:00
}];



ObjetImageConnexion.setDefinitionImages(lImages);
}
},fn:"imagesconnexion.js"});